#ifndef EVENT_H
#define EVENT_H

#include "Any.h"

namespace CCPlayer
{

class IMessageReceiver;

enum MessageType
{
//this is for client control the player
    COMMAND_TYPE_ENUM_OPEN = 0,
    COMMAND_TYPE_ENUM_PAUSE,
    COMMAND_TYPE_ENUM_CONTINUE,
    COMMAND_TYPE_ENUM_STOP,

    MESSAGE_TYPE_ENUM_INIT_GLRENDER_OBJECT,

//this is for player control the all modules
    MESSAGE_TYPE_ENUM_OPEN_FILE,
    MESSAGE_TYPE_ENUM_OPENED_FILE,

    MESSAGE_TYPE_ENUM_FINDED_AUDIO_STREAM,  //current is 5
    MESSAGE_TYPE_ENUM_FINDED_VIDEO_STREAM,

    MESSAGE_TYPE_ENUM_GET_AUDIO_PACKET,
    MESSAGE_TYPE_ENUM_GET_AUDIO_FRAME,
    MESSAGE_TYPE_ENUM_AUDIO_DECODER_READY,
    MESSAGE_TYPE_ENUM_AUDIO_RENDER_A_FRAME, //current is 10
    MESSAGE_TYPE_ENUM_AUDIO_DEOCDER_A_PACKET,
    MESSAGE_TYPE_ENUM_AUDIO_PAUSE,
    MESSAGE_TYPE_ENUM_AUDIO_CONTINUE,
    MESSAGE_TYPE_ENUM_AUDIO_DEADED,
    MESSAGE_TYPE_ENUM_GET_VIDEO_PACKET,
    MESSAGE_TYPE_ENUM_GET_VIDEO_FRAME,       //current is 15
    MESSAGE_TYPE_ENUM_VIDEO_DECODER_READY,
    MESSAGE_TYPE_ENUM_VIDEO_RENDER_A_FRAME,
    MESSAGE_TYPE_ENUM_VIDEO_DECODER_A_PACKET,
    MESSAGE_TYPE_ENUM_VIDEO_PAUSE,
    MESSAGE_TYPE_ENUM_VIDEO_CONTINUE,         //current is 20
    MESSAGE_TYPE_ENUM_VIDEO_DEADED,

    MESSAGE_TYPE_ENUM_DATA_MANAGER_EOF,

    MESSAGE_TYPE_ENUM_GET_AUDIO_INFORMATION,
    MESSAGE_TYPE_ENUM_GET_VIDEO_INFORMATION,

    MESSAGE_TYPE_ENUM_CLIENT_STOP
};

struct Event
{
    IMessageReceiver* pSendModule;
    IMessageReceiver* pReceiveModule;
    MessageType type;
    Any anyParams;
};

}

#endif
